# Generated by Django 4.0.2 on 2022-02-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=6, null=True)),
                ('first_name', models.CharField(blank=True, max_length=24, null=True)),
                ('last_name', models.CharField(blank=True, max_length=24, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=24, null=True)),
                ('email_address', models.CharField(blank=True, max_length=24, null=True)),
                ('company_name', models.CharField(blank=True, max_length=24, null=True)),
                ('address', models.CharField(blank=True, max_length=24, null=True)),
                ('city', models.CharField(blank=True, max_length=24, null=True)),
                ('country', models.CharField(blank=True, max_length=24, null=True)),
                ('state', models.CharField(blank=True, max_length=24, null=True)),
                ('post_code', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
