# Generated by Django 4.0.2 on 2022-02-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldWork',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=16, unique=True)),
                ('source', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('inventory_date', models.DateField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('date_year', models.TextField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, null=True)),
                ('signature_and_writing', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('size_note', models.TextField(blank=True, null=True)),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('file1', models.TextField(blank=True, null=True)),
                ('file2', models.TextField(blank=True, null=True)),
                ('file3', models.TextField(blank=True, null=True)),
                ('file4', models.TextField(blank=True, null=True)),
                ('file5', models.TextField(blank=True, null=True)),
                ('url1', models.TextField(blank=True, null=True)),
                ('url2', models.TextField(blank=True, null=True)),
                ('url3', models.TextField(blank=True, null=True)),
                ('url4', models.TextField(blank=True, null=True)),
                ('url5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
