# Generated by Django 4.0 on 2022-01-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
