# Generated by Django 4.0.2 on 2022-02-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=16, unique=True)),
                ('source', models.CharField(choices=[('Aldo foundation', 'Aldo foundation'), ('Anna', 'Anna'), ('Gifted', 'Gifted')], default='Aldo foundation', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('inventory_date', models.DateField()),
                ('title', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('date_year', models.TextField(blank=True, null=True)),
                ('medium', models.TextField(blank=True, null=True)),
                ('signature_and_writing', models.TextField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Painting', 'Painting'), ('Photography', 'Photography'), ('Sketch Pad', 'Sketch Pad'), ('Electromedia', 'Electromedia'), ('Videograms', 'Videograms'), ('Poetry Poster', 'Poetry Poster'), ('Notebook', 'Notebook'), ('Album', 'Album')], default='Painting', max_length=16)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('size_note', models.TextField(blank=True, null=True)),
                ('file1', models.CharField(blank=True, max_length=32, null=True)),
                ('file2', models.CharField(blank=True, max_length=32, null=True)),
                ('file3', models.CharField(blank=True, max_length=32, null=True)),
                ('file4', models.CharField(blank=True, max_length=32, null=True)),
                ('file5', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
