# Generated by Django 4.0.2 on 2022-02-02 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='inventory_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 22, 4, 9, 367395)),
        ),
    ]
