# Generated by Django 4.0 on 2022-01-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldwork',
            name='value',
            field=models.IntegerField(blank=True, max_length=32, null=True),
        ),
    ]
