# Generated by Django 4.0 on 2022-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_oldwork_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldwork',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
