# Generated by Django 4.0 on 2022-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_oldwork_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldwork',
            name='inventory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
