# Generated by Django 4.0.2 on 2022-02-05 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_inventory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='inventory_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 5, 0, 3, 36, 118450), null=True),
        ),
    ]
