# Generated by Django 4.0.2 on 2022-02-05 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_work_inventory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='inventory_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 5, 0, 52, 58, 654796), null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
