# Generated by Django 4.0 on 2022-01-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_oldwork_inventory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldwork',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldwork',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldwork',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
